adobe/parliament-client-template

- gatsby-node.js
- plugins/navigation-files-transformer/gatsby-node.js
- plugins/navigation-files-transformer/src/__tests__/__snapshots__/utiils.test.js.snap
- plugins/navigation-files-transformer/src/__tests__/fromJson.test.js
- plugins/navigation-files-transformer/src/__tests__/fromYaml.test.js
- plugins/navigation-files-transformer/src/__tests__/utiils.test.js
- plugins/navigation-files-transformer/src/fromJson.js
- plugins/navigation-files-transformer/src/fromYaml.js
- plugins/navigation-files-transformer/src/utils.js
- src/templates/indexTemplate.js
- src/templates/markdownTemplate.js
- src/templates/openapiTemplate.js
- src/templates/recipeTemplate.js
The side nav data is put in the DB by the `navigation-transformer-files` plugin. We are now reading the side nav content from the graphql DB in our page templates. Also cleared out a lot of code we don't need in gatsby-node.js anymore.
n/a
This sets us up to support multiple data formats for side nav. `navigation-transformer-files` can read the manifest from a JSON or YAML file but then it doesn't matter to the page templates as they get the info out of the DB. Makes life way easier.
> Read SideNav information from graphql

- src/components/seo.js
This PR adds the adobe-clean fonts per design using a typekit link. Not sure if that's the proper method for using fonts for the site. If not, let me know and I'll modify it.
[Issue 12:](https://github.com/adobe/parliament-client-template/issues/12) Parliament is not using Adobe Clean font by default
Adhering to typography/Adobe brand of fonts. And I was tired of seeing the light-weight Source Sans font that my system was determined to use. :)
I used a local clone of the analytics-2.0-apis repo.
- [?] My code follows the code style of this project.
> Updated site font to adobe-clean

- configs/development.js
- configs/production.js
Depending on if we are building from github or git.corp set the API url corrrectly
DEVEP-2331
We were hardcoding to git.corp and that means github repos would fail to build.
Running gatsby develop and build
> 🐛  Determine git api url based on GATSBY_SOURCE

- package.json
- scripts/markdown-cleaner/addLineBreaks.js
- scripts/markdown-cleaner/cleanHtmlNodes.js
- scripts/markdown-cleaner/index.js
- scripts/markdown-cleaner/markdownCleaner.js
- src/components/componentsMapping.js
- yarn.lock
This PR adds a script that formats and fixes HTML tags that break the MDX/JSX processing of markdown files. Existing markdown files often contain HTML tags. And some of these HTML tags break the build when the new MDX markdown processor (used in gatsby-theme-parliament and parliament-client-template) tries to parse them.
This plugin fixes those HTML tags by either converting them to proper CommonMark markdown or closing the tags so that they are interpreted as valid JSX by the MDX parser.
- https://github.com/adobe/gatsby-theme-parliament/issues/25
- https://github.com/adobe/gatsby-theme-parliament/issues/19
Markdown should be as pure as possible, without HTML tags that will cause issues in building and displaying markdown content. Using MDX as a superset of CommonMark opens up a world of …
> Markdown cleaner plugin for smooth MDX processing: Take 2

- gatsby-config.js
If the pattern definition has a whitespace e.g. `**/*, !config/**` the condition `pattern.startsWith("!")` will fail since the pattern is starting with a ' ' whitespace, hence it is important to remove all whitespaces from the patterns before splitting by a comma.
> 🐛 remove whitespaces from patterns

- gatsby-node.js
Detects if a swagger file will not build due to graphql limitations
DEVEP-2599
Certain swagger files will cause the build to fail. If they have an empty path key "" that is not a valid key name in graphql.
Tested locally with gatsby develop/build/serve
> 🐛  DEVEP-2599: OpenAPI spec with empty path name fails to build

- src/templates/markdownTemplate.js
Determines the correct path to edit the file in github
DEVEP-2652
To fix the Edit in Github link
> 🐛  DEVEP-2652: Edit in Github link broken

- package.json
- scripts/updateSearch.js
- scripts/writeInlineImages.js
- src/components/componentsMapping.js
- src/components/inlineImages.js
- yarn.lock
Read SVG components created by Markdown Cleaner
DEVEP-2597
Keeps inline svg's from breaking the build.
> Read SVG components created by Markdown Cleaner

- gatsby-node.js
- src/components/CourseNav.js
- src/components/NextPrev.js
- src/components/SiteMenu.js
- src/markdown-pages/do-not-delete.md
- src/templates/course.js
- basic building blocks for course templates
- use local store just to note which course pages you have visited
- render course nav a specific way based on tree depth
Huge thanks to @macdonst for holding my hand through the majority of this!
N/A
To teach courses via Parliament, sourcing material from markdown files.
Local manual testing with a course repository (details in slack).
> Courses, LocalStore, Nav w/ Max Depth!

- package.json
- src/components/doclayout.js
- yarn.lock
Extend the headers to include custom defined tabs from the `manifest.yaml` file.
Change follows from: https://github.com/adobe/parliament-transformer-navigation/pull/9
This change allows us to add custom tabs to the header. This is useful to link important external links (Swagger docs, Storybook etc)
Tested it locally.
- Change does not break if no tabs are specified in the manifest
- Change has been tested with and without the blog
- Change has been tested with absolute and relative hrefs
To enable tabs you will need to extend the `manifest.yaml` as such:
```
type: navigation
order: 1
title: Some Docs
pages:
- title: Overview
url: docs/guide/overview.md
- title: Workflows
url: docs/guide/workflows/introduction.md
tabs:
- title: Swagger APIs
url: https://host/api/v1/swagger-ui.html
- …
```
> DEVEP-2694 Support custom header tabs

- src/components/NextPrev.js
- src/components/ProgressBar.js
- src/templates/course-catalog.js
- src/templates/course.js
- src/util/course.js
- src/util/localstore.js
Fix for `NextPrev` bug introduced in #298 and add nav links in course progress.
- `NextPrev` callback was accidentally omitted during the refactor in #298 
- initialize localstore data with `false` visited keys on load
- allow users to navigate between modules using the progress wizard on course right-hand-side
N/A
Bugfix & QoL improvement.
Locally
> Course Nav: Fixes & Enhancements

- .github/workflows/ci.yml
Just realized that Actions were only being triggered if a PR was pushed to, not _opened_. 🤦‍♂️
Include `opened` & `reopened` events for CI Action workflow.
N/A
CI is nice. If it actually runs. LOL.
We'll see in this PR 😄 
N/A
> 🛠CI: include opened PRs

- src/components/SiteMenu.js
- src/templates/course-catalog.js
- src/templates/course.js
Pull in changes from https://github.com/adobe/parliament-ui-components/pull/172 to fix Edu template SiteNavs
N/A
Nav rendered all the things. 😢 
Locally
N/A
> 📓 Edu Templates: fix nav depth

- gatsby-config.js
- package.json
- yarn.lock
Adding @adobe/parliament-source-jsonschema to the project so we can source json schema files from the GraphQL database.
DEVEP-2770
So we can create pages based off of JSON Schema files
> Add @adobe/parliament-source-jsonschema to project

- package.json
- src/templates/course-catalog.js
- src/templates/quiz.js
- yarn.lock
Allows for nesting of courses in directories.
Before, courses would only exist in the catalog if they were in `<dir>/<course-name>/README.md`. Now you can embed them in more dirs.
N/A
Courses embedded a few levels deeper were not showing up.
Locally
> ᛦ course-catalog: allow courses to be in any dir

- gatsby-node.js
- package.json
- src/templates/json-schema.js
- yarn.lock
Add support for JSON Schema pages
DEVEP-2782
Allows folks to include JSON Schema files in their repos and have them be displayed as HTML pages.
> Devep 2770

- package.json
- src/components/componentsMapping.js
- yarn.lock
Allow JSON Schema's to be embedded in markdown docs
DEVEP-2784
Just in case folks want to embed JSON Schema's in their markdown files
> 🎉  DEVEP-2784: Allow JSON Schema's to be embedded in markdown docs

- src/components/layout.css
Fixes and issue where the ➡️  and ⬇️  don't show up for details/summary items.
DEVEP-2819
Without the icon it's hard to tell that the section is clickable.
gatsby develop/build/serve 
- [x ] Bug fix (non-breaking change which fixes an issue)
> 💄  DEVEP-2819: JSON Schema properties section are not obvious in Chrome

- src/templates/openapi.js
Fixes "Back to Docs" broken links for redoc open api pages
Fixes "Back to Docs" broken links for redoc open api pages
Tested locally and DEV region
> 🚀 back to docs fix

- src/templates/course.js
- src/templates/quiz.js
- src/util/index.js
this was written before the distinction between Curriculum vs Course was made
`dirname` no longer exists in the context where a course is an entire project
Should fix this issue:
Locally
See above.
> findSelectedPageNextPrev: remove dir requirement

- src/components/CourseNav.js
- src/templates/course.js
- src/templates/quiz.js
Makes the enable/disable logic around nav links for courses a bit less strict; allows for prepends to page paths.
Locally
> CourseNav: moduleCanBeNavigatedTo util arrow fx

- src/components/CourseMenu.js
- src/components/CourseNav.js
- src/templates/course.js
- src/templates/quiz.js
- use `gatsby.Link` for course nav
- rename a few props in `CourseNav` and `CourseMenu` so it's more obvious which variables are being used for what
- use `withPrefix` to account for localstore containing page fullpaths; page objects themselves only have page paths specified in their manifests, no prefixes.
Fixes a bug with the CourseNav in course templates.
Locally (build + `yarn start`)
> More Link Fixes

- src/components/PageActions.js
- Improved readability of TOC sidebar by adding some padding between each item
- Client originally asked for line-wrapping around each item but since that was resolved in a previous PR, this PR aims to improve the readability, especially for longer TOC items.
**Before**
**After**
> Add spacing to improve readability for TOC sidebar

- src/components/PageActions.js
Fixes the data structure that is passed for the "On This Page" Table of Contents component
* Re-worked the function which nests the headings for consumption by the ToC component
#398
Tested with affected pages and some test pages with various degrees of nesting/headings.
> Fix ToC data structure

- gatsby-node.js
Attempts to add HTML title fallback for pages that are not listed in `manifest.yaml`, or that are missing titles.
Fixes #402
> Add HTML title fallback for non-manifested pages

- Dockerfile.ci
- jest.config.js
- package.json
- src/templates/author.jsx
- src/templates/tag.jsx
- yarn.lock
Reapplies #406 after being reverted in #408.
> Redo "Upgrade to Node.js 18"

- src/components/layout.css
turns off font ligatures in code blocks.
#413
It looks bad and is harder to read.
In the brower, via dev-tools on the class declaration in question.
Note `font-variant-ligatures: no-common-ligatures` does not help.
(also note the screen-shot text was also edited in dev-tools, I don't remember where I found the original issue).
> disable ligatures in monospace code blocks.

- src/components/layout.css
* disable ligatures in monospace code blocks.
* Fix ordering
Contributed from #414 (@sparecycles).
---------
> disable ligatures in monospace code blocks

- gatsby-node.js
This PR omits HTML comments in Markdown documents from being indexed for search.
In certain circumstances, Markdown documents may contain HTML comments, such as:
```markdown
Some text between comments
Some more text
```
Indexing those comments is undesirable since those comments don't end up in the final rendered document.
This PR omits such comments so that only the target content is included in the search index.
> Do not index HTML comments in Markdown documents

- src/components/layout.css
- Set 'margin-bottom' to 0
N/A
We noticed how Table components show a horizontal show bar always regardless of whether the table overflows its parent container. We fixed this in https://github.com/adobe/parliament-ui-components/pull/200 by setting overflow-x to 'auto'. Besides the horizontal scroll bar, we noticed that table components have a bottom margin. We think we should not add this margin to all tables because of the following reasons.
* The margin makes the layout inconsistent - while tables have a bottom margin, they don't have a top margin.
* Doc authors cannot remove whitespace but can add it by adding breaklines - so, better too little margin than to much.
Ran Parliament locally with this change - table bottom margin gone.
_Before_
_After_
Note how there still is some …
> Remove bottom margin from tables

- gatsby-config.js
Disables contributor lookup as it currently fails, and would exceed API quota limit even if it worked.
> Disable contributors lookup
