adobe/parliament-client-template

- gatsby-node.js
Fixes broken elasticlunr search after MDX conversion.
Fun to fix things.
Tested on our handy test site and page builder docs repo
> Fixed search after conversion to MDX

- configs/global.js
- gatsby-node.js
- src/templates/markdownTemplate.js
- src/templates/openapiTemplate.js
- src/templates/recipeTemplate.js
Replaces Gatsby specific data in meta tags
#24 
We should use the info from the project itself instead of the default Gatsby template.
Running gatsby dev, build and serve to test the meta tags are updated.
> 🐛  Issue #24: Link Description is for Gatsby

- configs/global.js
- gatsby-browser.js
- package.json
- src/components/componentsMapping.js
- src/components/doclayout.js
- yarn.lock
Use our slick new Code component
n/a
Because it is beautiful and it adds the copy button which is sweet.
Tested in storybook in the ui components library then gatsby develop/build here.
> 🖼️  Use updated Code component

- configs/development.js
- configs/production.js
🐛 removing whitespaces from the pattern
whitespaces in patterns are causing problem for sourcing files into Gatsby
Identified this issue in one of the onboarding projects
Tested locally
- [x ] Bug fix (non-breaking change which fixes an issue)
> 🐛 removing whitespaces for pattern

- gatsby-node.js
- package.json
- src/components/HeaderBar.js
- yarn.lock
Use the header from UI components
n/a
Use the common header so we can use the same component in multiple projects.
After testing in Storybook in the UI components I've tested in gatsby develop and build.
> 🖼️  Use Header from ui components

- configs/development.js
- configs/production.js
- gatsby-node.js
- package.json
- src/components/PageActions.js
- src/components/layout.css
- src/images/adobe_logo-2.svg
- src/templates/markdownTemplate.js
- yarn.lock
Add contributors to the bottom of markdown pages
n/a
Let's folks know who has edited the file last. It now shows the correct time the file was last edited and not the last build time.
Gatsby develop and build
> Contributors

- gatsby-node.js
- package.json
- src/components/BioImage.js
- src/components/bio.js
- src/markdown-pages/do-not-delete.md
- src/templates/author.jsx
- src/templates/authors.js
- src/templates/blog-index.js
- src/templates/blog-post.js
- src/templates/markdownTemplate.js
- src/templates/openapiTemplate.js
- src/templates/recipeTemplate.js
- src/templates/tag.jsx
- yarn.lock
If the documentation repo has a `/blog` folder these changes will automatically create a blog tab in the header and process all the markdown files in that folder and it's sub-folder to create a blog.
n/a
Provides a common location where blog posts are located and processed. Enables us to roll them all up into the main blog site.
Running gatsby develop and build
> Add Blog functionality

- package.json
- yarn.lock
> 💡Upgrading parliament navigation package

- package.json
- yarn.lock
Using latest parliament-transform-navigation and parliament-ui-components
> Bump version for improving site navigation

- scripts/updateSearch.js
Protect routes with x-api-key
Adding x-api-key to search endpoint requests that mutate data.
> Protect routes with x-api-key

- gatsby-config.js
- gatsby-node.js
- package.json
- src/markdown-pages/do-not-delete.md
- src/templates/blog-index.js
- src/templates/blog-post.js
- src/templates/changelogTemplate.js
- src/templates/markdownTemplate.js
- src/templates/openapiTemplate.js
- src/templates/recipeTemplate.js
- yarn.lock
Add Changelog functionality if there is a changelog folder.
n/a
Give folks an easy way to display a nice changelog with minimal effort.
Tested in multiple repos where there is a combination of docs, blogs and changelog.
> Add Changelog functionality

- scripts/updateSearch.js
Skip sending the search index to our search engine if the project is not visible.
n/a
Private projects should not show up in the search engine results.
Tried with various values of VISIBLE.
> 🐛  Private projects should not be searchable

- README.md
- gatsby-config.js
Allow users to specify patterns of files/directories to ignore
n/a
Some files may cause build errors and we should be able to ignore them.
Tested locally using gatsby develop/build/serve
> Add ignore patterns

- gatsby-config.js
- package.json
- yarn.lock
> Switch to gatsby-source-parliament

- src/components/doclayout.js
- src/templates/markdownTemplate.js
- src/templates/openapiTemplate.js
Fixes side nav menu on mobile
DEVEP-2655
Fix mobile navigation
> 🐛  DEVEP-2655: Side menu broken on mobile

- README.md
First-time local dev env setup notes.
Update the comments in the sample `.env.development` to include explanations & requirements.
N/A
Local dev environment setups are always hard.
Fresh-clone & running into various walls.
N/A
> README: add context/notes in .env.development

- package.json
- src/components/ExperimentalBadge.jsx
- src/components/ProgressBar.js
- src/templates/course-catalog.js
- src/templates/course.js
- yarn.lock
Bucket touched courses, experimental badge, progress wizard.
- Add a progress wizard for course templates
- `ExperimentalBadge` because this is prone to...my bad code
- Courses can be "completed" now and `NextPrev` navigation stops based on dir
N/A
Ethos needs a proof-of-concept to show around.
Locally - ran app & ran `yarn build`
> Course & Chachkies 

- .eslintrc.js
- gatsby-node.js
Support Blog only projects
DEVEP-2684
Some projects may not have doc/open api files, only blog posts so we shouldn't show the "Docs" tab in that case.
Gatsby develop/build/serve
> 🖼️  DEVEP-2684: Blog-only projects in Parliament

- CODEOWNERS
CODEOWNERS file. More details in file itself.
Trying to lock down access for sensitive workflow paths.
N/A
Just want to keep us safe & secure
Would need this file merged 😖 
N/A
> 🔒 CODEOWNERS: lock who can change important files

- src/components/HeaderBar.js
Removes error in the console
n/a
Gets rid of an error in the console that can easily be avoided by changing the way props are passed into the header
> 👕  Remove gitRemote error in console

- src/components/ProgressBar.js
- src/components/ProgressBarDrawer.js
- src/templates/course.js
- yarn.lock
Move the progress nav/bar into an `rsuite` drawer. Was causing too many issues.
TODO: figure out how to make it respect dark-mode 😭 
N/A
Larger/longer progress bars were causing all kinds of UI issues.
Locally 🥳
> Courses: Progress Bar Tweaks

- src/templates/openapi.js
Go back to docs homepage instead of back one page
DEVEP-2683 
Customer request
> ⬅️  Go back to homepage from openapi spec

- README.md
- package.json
- src/util/cookie.js
- src/util/env.js
- yarn.lock
Add some supporting code to fetch values from cookies. Just for `OKTA_USERNAME` for the time being.
N/A
Required for some edu work on my local.
Locally.
N/A
> 🍪 👋  cookie.OKTA_USERNAME

- src/templates/openapi.js
> 🚀 back to docs fix

- gatsby-node.js
- src/templates/openapi.js
Fixes broken link issues for tags and authors
> Tag author fix

- gatsby-config.js
> 🐛 avoid git.corp rate limit

- src/templates/course.js
- src/templates/quiz.js
> courses & quizzes: pass in all pages to CourseMenu

- gatsby-node.js
> Add project path to search 

- gatsby-node.js
> Add project path to search

- gatsby-config.js
> 🐛 rollback check-links

- gatsby-config.js
- package.json
- yarn.lock
> 💡 adding yaml and json in ignore list for copy files

- Dockerfile.ci
- jest.config.js
- package.json
- src/templates/author.jsx
- src/templates/tag.jsx
- yarn.lock
This PR upgrades Gatsby to v4.25.7 to support Node.js 18.
> Upgrade to Node.js 18

- src/components/__tests__/HeaderBar.test.js
This PR fixes `HeaderBar.test`.
> Fix HeaderBar.test

- package.json
- yarn.lock
> Upgrade gatsby-remark-afm

- package.json
- yarn.lock
This PR upgrades `@adobe/parliament-ui-components` to v5.2.3 to take advantage of the `redoc` upgrade introduced in adobe/parliament-ui-components#199.
> Upgrade parliament-ui-components

- package.json
- yarn.lock
Reverts adobe/parliament-client-template#411
> Revert "Upgrade parliament-ui-components"

- gatsby-node.js
Follow-up to #416 but specifically for HTML comments in page titles.
> Do not index HTML comments in titles

- gatsby-node.js
This PR fixes the `getTitle` function to extract Markdown headings and fallback to the first non-empty line otherwise.
> Fix getTitle

- src/components/layout.css
> Remove table bottom margin (#419)

- gatsby-node.js
> Fix bug in gatsby-node.js

- gatsby-config.js
- package.json
- yarn.lock
> Support mermaid

- gatsby-config.js
Reverts adobe/parliament-client-template#424
> Revert "Disable contributors lookup"

- gatsby-config.js
- gatsby-node.js
> Disable contributors lookup

- scripts/updateSearch.js
This PR disables the search update due to the following JS heap error that results in crashing the backend server:
```
2025-04-21T23:46:49.463Z | <--- Last few GCs --->
2025-04-21T23:46:49.463Z | 
2025-04-21T23:46:49.463Z | [3452:0x55bedc267b60]   187639 ms: Mark-sweep 1175.4 (1275.0) -> 1175.3 (1274.5) MB, 865.6 / 0.0 ms  (average mu = 0.414, current mu = 0.000) last resort GC in old space requested
2025-04-21T23:46:49.463Z | [3452:0x55bedc267b60]   188522 ms: Mark-sweep 1175.3 (1274.5) -> 1175.3 (1274.5) MB, 883.2 / 0.0 ms  (average mu = 0.257, current mu = 0.000) last resort GC in old space requested
2025-04-21T23:46:49.463Z | 
2025-04-21T23:46:49.463Z | 
2025-04-21T23:46:49.463Z | <--- JS stacktrace --->
2025-04-21T23:46:49.463Z | 
2025-04-21T23:46:49.463Z | ==== JS stack trace …
```
> Disable updateSearch.js
